const mock = [
  {
    fairings: {
      reused: null,
      recovery_attempt: null,
      recovered: null,
      ships: [],
    },
    links: {
      patch: {
        small: 'https://imgur.com/BrW201S.png',
        large: 'https://imgur.com/573IfGk.png',
      },
      reddit: {
        campaign: 'https://www.reddit.com/r/spacex/comments/jhu37i/starlink_general_discussion_and_deployment_thread/',
        launch: null,
        media: null,
        recovery: 'https://www.reddit.com/r/spacex/comments/k2ts1q/rspacex_fleet_updates_discussion_thread/',
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: null,
      youtube_id: null,
      article: null,
      wikipedia: 'https://en.wikipedia.org/wiki/Starlink',
    },
    static_fire_date_utc: null,
    static_fire_date_unix: null,
    net: false,
    window: null,
    rocket: '5e9d0d95eda69973a809d1ec',
    success: true,
    failures: [],
    details: null,
    crew: [],
    ships: [],
    capsules: [],
    payloads: [
      '61e05516be8d8b66799018d4',
    ],
    launchpad: '5e9e4502f509094188566f88',
    flight_number: 146,
    name: 'Starlink 4-6 (v1.5)',
    date_utc: '2022-01-18T00:16:00.000Z',
    date_unix: 1642464960,
    date_local: '2022-01-17T19:16:00-05:00',
    date_precision: 'hour',
    upcoming: true,
    cores: [
      {
        core: null,
        flight: null,
        gridfins: true,
        legs: true,
        reused: true,
        landing_attempt: true,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    auto_update: true,
    tbd: false,
    launch_library_id: '50ac28f2-024f-442f-837d-dab8107304ec',
    id: '61e048bbbe8d8b66799018d0',
  },
  {
    fairings: {
      reused: null,
      recovery_attempt: null,
      recovered: null,
      ships: [],
    },
    links: {
      patch: {
        small: null,
        large: null,
      },
      reddit: {
        campaign: null,
        launch: null,
        media: null,
        recovery: null,
      },
      flickr: {
        small: [],
        original: [],
      },
      presskit: null,
      webcast: null,
      youtube_id: null,
      article: null,
      wikipedia: null,
    },
    static_fire_date_utc: null,
    static_fire_date_unix: null,
    net: false,
    window: null,
    rocket: '5e9d0d95eda69973a809d1ec',
    success: null,
    failures: [],
    details: null,
    crew: [],
    ships: [],
    capsules: [],
    payloads: [
      '6161d3a06db1a92bfba8535a',
    ],
    launchpad: '5e9e4501f509094ba4566f84',
    flight_number: 147,
    name: 'CSG-2',
    date_utc: '2021-01-27T23:11:00.000Z',
    date_unix: 1611789060,
    date_local: '2022-01-27T18:11:00-05:00',
    date_precision: 'hour',
    upcoming: true,
    cores: [
      {
        core: null,
        flight: null,
        gridfins: null,
        legs: null,
        reused: null,
        landing_attempt: null,
        landing_success: null,
        landing_type: null,
        landpad: null,
      },
    ],
    auto_update: false,
    tbd: false,
    launch_library_id: null,
    id: '6161d32d6db1a92bfba85359',
  },
];

export default mock;
